# Generated by Django 3.0.5 on 2020-09-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherDataRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('min_temp', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('mean_temp', models.FloatField()),
                ('heat_degree_days', models.FloatField()),
                ('total_rain', models.FloatField()),
                ('total_snow', models.FloatField()),
                ('speed_max_gusts', models.FloatField()),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.UploadedDocument')),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
