# Generated by Django 3.0.5 on 2020-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_uploadeddocument_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdatarow',
            name='heat_degree_days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='max_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='mean_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='min_temp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='speed_max_gusts',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='total_rain',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weatherdatarow',
            name='total_snow',
            field=models.FloatField(default=0),
        ),
    ]
