# Generated by Django 3.0.5 on 2020-09-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20200902_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdatarow',
            old_name='date_time',
            new_name='date',
        ),
    ]
